[tool.poetry]
name = "progetto-one"
version = "0.1.0"
description = ""
authors = ["<leonardo.viola.19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
